name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      # Cache the Next.js build cache
      - name: Cache Next.js build
        uses: actions/cache@v4
        with:
          path: personal-website/.next/cache
          key: ${{ runner.os }}-nextjs-${{ hashFiles('personal-website/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-nextjs-
      
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18
          # Disable the built-in caching mechanism of setup-node
          cache: false
      
      - name: Setup Pages
        uses: actions/configure-pages@v4
      
      - name: Install dependencies
        run: cd personal-website && npm ci
      
      - name: Build
        run: cd personal-website && npm run build -- --no-lint
      
      - name: Create CNAME file
        run: echo "yousefowili.me" > personal-website/out/CNAME
      
      - name: List directories for debugging
        run: |
          echo "Contents of personal-website/out:"
          ls -la personal-website/out/
      
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: personal-website/out

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4 