name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'
          cache-dependency-path: 'personal-website/package-lock.json'

      - name: Install dependencies
        run: cd personal-website && npm ci

      - name: Build
        run: cd personal-website && npm run build

      - name: Copy build output to root
        run: |
          rm -rf *.html *.txt *.svg *.ico _next images 404
          cp -r personal-website/out/* .
          touch .nojekyll

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: .
          branch: gh-pages
          clean: true 