name: Manual Next.js Deploy

on:
  workflow_dispatch:
    inputs:
      deploy_message:
        description: 'Deployment message'
        required: true
        default: 'Manual deployment'

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18

      # Explicitly create .nojekyll file
      - name: Create .nojekyll file
        run: touch .nojekyll
        
      # Display package.json for debugging
      - name: Display package.json
        run: cat package.json
        
      # Clean install without using cache
      - name: Install dependencies
        run: |
          echo "Installing dependencies..."
          npm ci --no-cache

      # Display installed packages
      - name: List installed packages
        run: npm list --depth=0
        
      # Build with Next.js without linting
      - name: Build with Next.js (without linting)
        run: |
          echo "Building Next.js site without linting..."
          npm run build -- --no-lint
          
      # List output directory contents
      - name: List output directory
        run: |
          echo "Checking output directory..."
          ls -la
          if [ -d "out" ]; then
            echo "Contents of out directory:"
            ls -la out/
          else
            echo "out directory not found!"
            echo "Checking for other possible output directories:"
            ls -la .next/ || echo ".next directory not found"
          fi

      # Upload the build output
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./out

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
        with:
          token: ${{ github.token }} 