name: Deploy Next.js Site

on:
  # Manual trigger
  workflow_dispatch:
    inputs:
      deploy:
        description: 'Deploy the Next.js site'
        required: true
        default: 'yes'

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build-and-deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 16
          cache: 'npm'
          cache-dependency-path: 'personal-website/package-lock.json'

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Install dependencies
        run: |
          cd personal-website
          npm ci
          
      - name: List component files
        run: |
          cd personal-website
          echo "Files in components directory:"
          ls -la src/components/
          
      - name: Fix case sensitivity issues
        run: |
          cd personal-website
          # Create lowercase versions of all component files
          for file in src/components/*.tsx; do
            basename=$(basename "$file")
            lowercase=$(echo "$basename" | tr '[:upper:]' '[:lower:]')
            if [ "$basename" != "$lowercase" ]; then
              echo "Creating lowercase version of $basename as $lowercase"
              cp "$file" "src/components/$lowercase"
            fi
          done
          
          # Update imports in all files
          find src -name "*.tsx" -o -name "*.ts" | xargs grep -l "import.*from.*components" | while read file; do
            echo "Checking imports in $file"
            # Get all component imports
            grep "import.*from.*components" "$file" | while read import_line; do
              component=$(echo "$import_line" | grep -o "components/[A-Z][a-zA-Z]*" | cut -d'/' -f2)
              if [ ! -z "$component" ]; then
                lowercase=$(echo "$component" | tr '[:upper:]' '[:lower:]')
                echo "Updating import for $component to $lowercase in $file"
                sed -i "s/components\/$component/components\/$lowercase/g" "$file"
              fi
            done
          done
          
          # List files after changes
          echo "Files after case sensitivity fix:"
          ls -la src/components/

      - name: Update Next.js config
        run: |
          cd personal-website
          cat > next.config.js << EOL
          /** @type {import('next').NextConfig} */
          const nextConfig = {
            reactStrictMode: true,
            images: {
              unoptimized: true
            },
            output: 'export',
            trailingSlash: true,
          };
          
          module.exports = nextConfig;
          EOL

      - name: Build with TypeScript checks disabled
        run: |
          cd personal-website
          # Build with environment variables to bypass checks
          NEXT_TELEMETRY_DISABLED=1 NODE_OPTIONS="--max_old_space_size=4096" npm run build -- --no-lint

      - name: Create CNAME file
        run: echo "yousefowili.me" > personal-website/out/CNAME

      - name: List build output
        run: |
          echo "Contents of personal-website/out:"
          ls -la personal-website/out/

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: personal-website/out

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4 